### ISSUE TITLE
need veo directory?

### ISSUE THREAD

**Issue by kaz7** [SX-Aurora/py-veo#1]
Hi, thank you for publishing such a great project for Aurora.

When I try to install py-veo like below, it causes a following error.
```
$ make
$ sudo make install
CFLAGS="-I/opt/nec/ve/veos/include" \
LDFLAGS="-L/opt/nec/ve/veos/lib64 -Wl,-rpath=/opt/nec/ve/veos/lib64" \
python setup.py install
src/veo.pyx: cannot find cimported module 'libveo'
running install
running build
running build_py
error: package directory 'veo' does not exist
```

When I create an empty directory like below, it works fine.  You may forget to add a placeholder for an empty veo directory?
```
$ mkdir veo
$ sudo make install
```

Thanks.

**Comment by efocht** [comment]
Marukawa-san, I'm sorry for this very late reply. I changed the setup.py such that veo.so goes directly into the site-packages directory.

You should be able to install with
```
pip install py-veo
```
now. For building (during pip installation) you'll need the *veoffload-devel* RPM installed, as well as numpy. It works inside a virtualenv, as well. I only tried Python2.7...

Regards,
Erich
