### ISSUE TITLE
psutil is missing from setup.py

### ISSUE THREAD

**Issue by FreddieWitherden** [SX-Aurora/py-veo#2]
As per

https://github.com/SX-Aurora/py-veo/blob/master/veo/_veo.pyx#L17

there is a dependency on psutil however this is missing from `setup.py`.  This can lead to an import error after using pip to install veo in a fresh virtual environment.

**Comment by efocht** [comment]
In tag v1.4.0. Closing.

**Comment by FreddieWitherden** [comment]
So I think this needs to be added under the `install_requires` argument to `setup()`.  Currently it is under `requires` which, it appears, does not get it marked down as a dependency.

**Comment by keichi** [comment]
Just ran into this. Can you please fix the `setup.py` script @efocht? I will open a PR if you would like me to.

```
>>> import veo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.8.13/lib/python3.8/site-packages/veo/__init__.py", line 1, in <module>
    from veo._veo import *
  File "veo/_veo.pyx", line 17, in init veo._veo
ModuleNotFoundError: No module named 'psutil'
```
