### ISSUE TITLE
load_library and get_function should accept strings

### ISSUE THREAD

**Issue by FreddieWitherden** [SX-Aurora/py-veo#4]
On Python 3 when calling `load_library` and `get_function` it is necessary to pass bytes arrays as `b'libname.so'`.  This is somewhat irregular.  It would be more natural if these methods could accept ordinary Python (Unicode) strings and then encode them to UTF-8 in order to get char* buffers which can be passed to the C routines.

**Comment by efocht** [comment]
Should be fixed. Closing.
